# Generated by Django 5.2.7 on 2025-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COLLABORATOR', 'Colaborador')], default='COLLABORATOR'),
        ),
    ]
