# Generated by Django 5.2.7 on 2025-11-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_movementstock_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
